version: '3.2'

services:
  php:
    build:
      context: .
      dockerfile: php7.3-apache-with-memcached
    volumes:
      - ./src:/var/www/html
    ports:
      - "8008:80"
    links:
      - memcached
    restart: always
  memcached:
    image: memcached:1.5
